### PR TITLE
fine tweeks on h1 and collab links

### PR DESCRIPTION
**Pull request by MatthewScott32**
1. git fetch --all
2. git checkout execSum3
3. Check that you like the h1 as just "Celebrity Tribute" and like the format of the collaborations and links of collaboration names.

### CODE REVIEW

**Review by sullypierce — DISMISSED** [review]
looks just, just might want to set a min-width on body

**Review by melliemuse — DISMISSED** [review]
Looks good!

**Review by rdbishop19 — CHANGES_REQUESTED** [review]
Apply the link styling across the board to all html pages and should be good

**Review by sullypierce — APPROVED** [review]

**Review by rdbishop19 — COMMENTED** [review]
updates look good!

**Review by rdbishop19 — APPROVED** [review]
this should be good

**Pull request merged**
