### PR TITLE
Styling changes

### PR DESCRIPTION
**Pull request by melliemuse**
`git fetch --all`
`git checkout ms-careerStyling`
Verify everything looks ok and the links work- thanks!

### CODE REVIEW

**Review by MatthewScott32 — DISMISSED** [review]
looks good

**Review by sullypierce — DISMISSED** [review]
Looks great!

**Review by rdbishop19 — DISMISSED** [review]
everything looks good!

**Review by rdbishop19 — APPROVED** [review]
Bingo!

**Review by sullypierce — APPROVED** [review]

**Pull request merged**
