### PR TITLE
filled out main.css, moved h1 in each html, added a few classes in main

### PR DESCRIPTION
**Pull request by sullypierce**
1. `git fetch --all`
2. `git checkout sp-maincss`
3.  check main.css for mistakes
4.  check that h1 is moved to main in each html

### CODE REVIEW

**Review by MatthewScott32 — DISMISSED** [review]
Got it.  All is good.

**Review by rdbishop19 — DISMISSED** [review]
looks good

**Review by MatthewScott32 — APPROVED** [review]
looks good

**Review by rdbishop19 — APPROVED** [review]
i trust you

**Pull request merged**
